"""Generate the static search index from the 56 lesson HTML files.

Run `python tools/build_search_index.py` after editing lessons, or pass --check
to verify that the committed index is current without writing files.
"""

from __future__ import annotations

import argparse
from html.parser import HTMLParser
import json
from pathlib import Path
import re


VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}
SKIP = {"script", "style", "nav", "svg", "button"}


def clean(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


class LessonParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[str] = []
        self.content_depth: int | None = None
        self.title_parts: list[str] = []
        self.text_parts: list[str] = []
        self.headings: list[str] = []
        self.heading_tag: str | None = None
        self.heading_parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in VOID:
            return
        self.stack.append(tag)
        classes = dict(attrs).get("class") or ""
        if self.content_depth is None and tag == "div" and "content-area" in classes.split():
            self.content_depth = len(self.stack)
        if self.content_depth is not None and tag in {"h2", "h3", "h4"}:
            self.heading_tag = tag
            self.heading_parts = []

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag not in VOID:
            self.handle_starttag(tag, attrs)
            self.handle_endtag(tag)

    def handle_endtag(self, tag: str) -> None:
        if self.heading_tag == tag:
            heading = clean(" ".join(self.heading_parts))
            if heading:
                self.headings.append(heading)
            self.heading_tag = None
            self.heading_parts = []
        if tag in self.stack:
            index = len(self.stack) - 1 - self.stack[::-1].index(tag)
            del self.stack[index:]
        if self.content_depth is not None and len(self.stack) < self.content_depth:
            self.content_depth = None

    def handle_data(self, data: str) -> None:
        if "title" in self.stack:
            self.title_parts.append(data)
        if self.content_depth is None or any(tag in SKIP for tag in self.stack):
            return
        self.text_parts.append(data)
        if self.heading_tag is not None:
            self.heading_parts.append(data)


def build(root: Path) -> dict[str, object]:
    lessons: list[dict[str, object]] = []
    for day in range(1, 57):
        relative = Path(f"week{(day - 1) // 7 + 1}") / f"day{day:02}.html"
        source = root / relative
        if not source.is_file():
            raise ValueError(f"Missing lesson: {relative.as_posix()}")
        parser = LessonParser()
        parser.feed(source.read_text(encoding="utf-8"))
        raw_title = clean(" ".join(parser.title_parts))
        title = clean(re.split(r"\s+[—–-]\s+Giáo Trình", raw_title, maxsplit=1)[0])
        text = clean(" ".join(parser.text_parts))
        if not title or not text or not parser.headings:
            raise ValueError(f"Incomplete lesson content: {relative.as_posix()}")
        lessons.append({"id": f"day{day:02}", "url": relative.as_posix(), "title": title,
                        "headings": parser.headings, "text": text})
    return {"version": 1, "lessons": lessons}


def main() -> int:
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument("--check", action="store_true", help="fail if generated index differs")
    argp.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    args = argp.parse_args()
    root = args.root.resolve()
    output = root / "assets/js/search-index.js"
    try:
        data = build(root)
    except (OSError, ValueError) as exc:
        argp.exit(2, f"build_search_index: {exc}\n")
    content = "// Generated by tools/build_search_index.py. Do not edit by hand.\n"
    content += "window.EbookSearchIndex = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            print("Search index is missing or stale. Run: python tools/build_search_index.py")
            return 1
        print(f"Search index is current: {len(data['lessons'])} lessons, {output.stat().st_size} bytes")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {len(data['lessons'])} lessons to {output.relative_to(root).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
