"""Author P9-02 A22–A24 from a deterministic text/figure source."""

from __future__ import annotations

from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PICO_PDF = "https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf"
RP_PDF = "https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf"
PICO_DOC = "https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html"
PICO_SDK = "https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html"
MICROPY = "https://docs.micropython.org/en/latest/rp2/quickref.html"
PIN_DOC = "https://docs.micropython.org/en/latest/library/machine.Pin.html"
ESP_BOARD = "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html"
ESP_CHIP = "https://documentation.espressif.com/esp32-c6_datasheet_en.html"


LESSONS = [
    {
        "id": "a22", "title": "CPU, Bộ Nhớ, Bus & Hệ Xử Lý", "subtitle": "Đọc một hệ thực từ silicon đến board: 264 kB SRAM ở RP2040 khác 2 MB flash trên Pico.",
        "base": "A17, A21, D22", "units": "4", "figure_alt": "Sơ đồ khối học tập của Raspberry Pi Pico không dây đời đầu: hai lõi Cortex-M0+ trong RP2040 qua bus fabric tới SRAM 264 kB, ngoại vi và cổng QSPI/XIP; flash 2 MB nằm ngoài chip nhưng trên board Pico.",
        "figure_text": "Bản đồ khái niệm tự vẽ; flash 2 MB thuộc <strong>board Pico</strong>, SRAM 264 kB thuộc <strong>chip RP2040</strong>. Mũi tên là luồng truy cập, không phải netlist hoặc định thời bus.",
        "source": f'<a href="{RP_PDF}" target="_blank" rel="noopener">Raspberry Pi RP2040 datasheet §2.6</a> và <a href="{PICO_PDF}" target="_blank" rel="noopener">Pico board datasheet §1, Fig. 1 Rev3</a>',
        "transcript": "Hai lõi CPU Cortex-M0+ của RP2040 nối tới cấu trúc bus bên trong. Bus cho phép CPU và các bus master truy cập SRAM 264 kB on-chip, thanh ghi ngoại vi và vùng XIP/cache phục vụ flash QSPI. Flash 2 MB được gắn trên board Pico, bên ngoài gói RP2040. Sơ đồ không thể hiện thứ tự ưu tiên hay chu kỳ tranh chấp bus.",
        "objectives": ["Vẽ luồng CPU lấy lệnh/dữ liệu qua bus tới SRAM, flash và ngoại vi có thanh ghi ánh xạ địa chỉ.", "Phân biệt 264 kB SRAM thuộc RP2040 với 2 MB flash thuộc Pico board và tính một ngân sách nhớ giả định.", "Giải thích MCU/MPU/SoC là nhãn kiến trúc có thể chồng lấn, không thay dữ liệu board/part."],
        "body": f'''
<h2>1. Bốn lớp cần đọc riêng</h2>
<p><strong>CPU</strong> thực thi lệnh; <strong>bộ nhớ</strong> giữ lệnh/dữ liệu; <strong>bus</strong> chuyển giao các lần đọc/ghi; <strong>ngoại vi</strong> có thanh ghi điều khiển và kết nối tín hiệu. <a href="{RP_PDF}" target="_blank" rel="noopener">RP2040 datasheet §2.6</a> ghi SRAM on-chip tổng <code>264 kB</code> chia sáu bank vật lý. RP2040 có hai lõi Arm Cortex-M0+ và QSPI/XIP với cache; <a href="{PICO_PDF}" target="_blank" rel="noopener">Pico board datasheet §1</a> ghi <code>2 MB flash</code> nằm trên board. Không cộng 2 MB flash vào dung lượng SRAM của chip hoặc nói mọi board RP2040 đều gắn đúng flash này.</p>
<p>Trong một ví dụ firmware chạy từ flash qua XIP/cache, CPU lấy lệnh theo địa chỉ; biến/buffer có thể ở SRAM; đọc/ghi thanh ghi GPIO là truy cập ngoại vi được ánh xạ vào không gian địa chỉ. Cấu trúc bus giúp nhiều master tiếp cận tài nguyên, nhưng <strong>không</strong> suy rằng hai CPU luôn đọc cùng bank mà không tranh chấp hoặc rằng flash nhanh ngang SRAM. Sơ đồ A22-1 chỉ đường logic cấp hệ, không vẽ đường mạch QSPI.</p>
<h2>2. MCU, MPU và SoC</h2>
<p>RP2040 là ví dụ <strong>MCU</strong>: tích hợp CPU, SRAM và nhiều ngoại vi trong một chip; flash chương trình của Pico được nối ngoài chip. Từ <em>MPU</em> thường nhấn mạnh khối xử lý cần thêm bộ nhớ/ngoại vi ở cấp hệ, còn <em>SoC</em> nhấn mạnh nhiều chức năng tích hợp trên một chip. Các nhãn này không phải ba hộp loại trừ nhau và không cho biết GPIO, RAM, radio hay hệ điều hành nếu chưa đọc đúng mã chip/board. Một Raspberry Pi Pico chạy firmware MCU, không phải máy Raspberry Pi Linux chỉ vì chung thương hiệu.</p>
<h2>3. Ví dụ ngân sách nhớ có điều kiện</h2>
<p>Giả định image firmware có <code>128 KiB</code> và buffer dữ liệu cần <code>32 KiB</code>. Trên reference Pico, <code>128 KiB &lt; 2 MiB</code> flash board và <code>32 KiB &lt; 264 KiB</code> SRAM chip; buffer bằng <code>32/264≈12,1%</code> tổng SRAM vật lý. Đây mới là <strong>cổng dung lượng thô</strong>: còn bootloader/firmware, stack, heap, cache, vùng dành riêng, layout liên kết và độ bền flash. Với MicroPython, không được tự nhận còn đủ 232 KiB heap cho ứng dụng chỉ bằng phép trừ này.</p>
<h2>4. Hoạt động trên giấy</h2>
<div class="callout callout-practice"><div class="callout-header">🔬 Bản đồ tài nguyên</div><p>Vẽ ba khung: RP2040 chip, Pico board, thiết bị ngoài. Đặt CPU/SRAM/GPIO vào chip và flash 2 MB vào board; khoanh một đường lấy lệnh XIP và một đường ghi GPIO. Lập bảng “thuộc chip/board/chưa biết”, rồi kiểm từng dòng theo hai datasheet hãng. Với image/buffer giả định, tính tỷ lệ 32/264 và ghi điều kiện chưa biết trước khi quyết định chạy được.</p></div>
<div class="table-wrap"><table><caption>Đặt tài nguyên đúng cấp</caption><thead><tr><th>Tài nguyên</th><th>Cấp</th><th>Dữ kiện reference</th></tr></thead><tbody><tr><td>Hai Cortex-M0+, SRAM 264 kB, bus/ngoại vi</td><td>RP2040 silicon</td><td>Datasheet RP2040</td></tr><tr><td>Flash QSPI 2 MB</td><td>Pico board, ngoài chip</td><td>Pico datasheet</td></tr><tr><td>Heap còn trống sau firmware</td><td>Runtime cụ thể</td><td>Chưa đo/không suy từ tổng SRAM</td></tr></tbody></table></div>
<div class="callout callout-warning"><div class="callout-header">⚠️ Giới hạn revision</div><p>Fig. 1 của datasheet dùng board Rev3 làm hình tham khảo; không có board vật lý ở dự án để xác định PCB revision. Khi mua/lắp phải ghi board thực, firmware/toolchain và test log, nhất là khi chuyển sang Pico W/Pico 2 hoặc board RP2040 khác.</p></div>''',
        "exercise": "Một chương trình giả định có image 128 KiB và buffer 32 KiB. Chúng thường được đặt ở flash board hay SRAM chip trong ví dụ Pico? Tính phần trăm 32 KiB so với tổng 264 KiB SRAM. Có được kết luận còn đúng 232 KiB heap cho MicroPython không?",
        "answer": "<ol><li>1 điểm: image 128 KiB ở flash 2 MB trên Pico board trong mô hình chạy XIP.</li><li>1 điểm: buffer 32 KiB dùng SRAM thuộc RP2040 (nếu phần mềm bố trí như giả định).</li><li>1 điểm: <code>32/264≈12,1%</code> tổng SRAM vật lý; 128 KiB nhỏ hơn 2 MiB flash.</li><li>1 điểm: không suy heap còn 232 KiB vì runtime/stack/heap/firmware và phân bổ khác còn chiếm SRAM.</li></ol>",
        "checks": ["Tôi phân biệt tài nguyên chip và board", "Tôi chỉ vẽ đường bus ở mức khái niệm", "Tôi không coi tổng SRAM là heap trống"],
    },
    {
        "id": "a23", "title": "Ngoại Vi MCU & Lab GPIO Pico", "subtitle": "Dùng LED tích hợp trên Pico không W để kiểm chuỗi lệnh GPIO; timing host chỉ là lịch dự kiến.",
        "base": "A22, D25, D26", "units": "5", "figure_alt": "Sơ đồ Raspberry Pi Pico non-W tham khảo: GPIO GP25 của RP2040 điều khiển LED tích hợp trên board; timeline high 250 mili giây, low 250 mili giây lặp lại cho chu kỳ danh định 500 mili giây và tần số 2 hertz.",
        "figure_text": "Đường GP25→LED thuộc Pico non-W theo hãng; đồ thị là <strong>lịch lệnh danh định</strong>, không phải dạng sóng đo. GP25 điều khiển LED trên board, không là chân header đưa ra ngoài.",
        "source": f'<a href="{PICO_SDK}" target="_blank" rel="noopener">Raspberry Pi C SDK blink guide (Pico GP25/Pico W WL_GPIO0)</a>, <a href="{MICROPY}" target="_blank" rel="noopener">MicroPython RP2 quick reference</a>',
        "transcript": "GP25 của RP2040 trên Pico non-W đi tới LED tích hợp. Mã đặt GP25 làm output, khởi đầu low, rồi high 250 ms, low 250 ms lặp lại. Lý tưởng t=0 high, t=250 ms low, t=500 ms high, t=750 ms low; chu kỳ lệnh 500 ms. Hình không vẽ điện trở/nguồn/pad đo, và không áp cho Pico W hay ESP32-C6 board.",
        "objectives": ["Phân biệt GPIO, timer, ADC, DMA và IRQ theo việc CPU giao tiếp/thời điểm lấy mẫu.", "Tái lập lab GP25 LED trên Pico non-W bằng mã MicroPython và đối chiếu lệnh bằng fake Pin trên host.", "Tính chu kỳ/frequency/duty danh định và nêu lý do lịch lệnh không bằng phép đo jitter của board."],
        "body": f'''
<h2>1. Ngoại vi làm gì?</h2>
<p>GPIO xuất/đọc mức số; timer tạo mốc thời gian; ADC đổi điện áp analog thành mã số; DMA chuyển dữ liệu theo cấu hình mà CPU không phải tự sao chép từng phần tử; IRQ báo sự kiện để CPU chạy handler. Chúng thường có thanh ghi điều khiển được truy cập qua bus. Cần phân biệt <em>đặt một lệnh GPIO</em> với <em>đo điện áp tại pad</em>, và <em>sleep theo phần mềm</em> với một waveform timer/PWM phần cứng. <a href="{RP_PDF}" target="_blank" rel="noopener">RP2040 datasheet</a> là nguồn để tra peripheral và giới hạn thực; A23 chỉ làm lab GPIO.</p>
<h2>2. Lab có mã và điều kiện board</h2>
<p>Chọn <strong>Raspberry Pi Pico đời đầu không W</strong>, tài liệu board minh họa Rev3. <a href="{PICO_SDK}" target="_blank" rel="noopener">Raspberry Pi C SDK guide</a> xác nhận LED Pico ở GP25, còn Pico W nối LED qua wireless chip <code>WL_GPIO0</code>. Mã <a href="../labs/pico_gpio_blink.py">pico_gpio_blink.py</a> dùng <a href="{PIN_DOC}" target="_blank" rel="noopener">MicroPython <code>machine.Pin</code></a> và <code>sleep_ms</code>: tạo <code>Pin(25, Pin.OUT, value=0)</code>, ghi 1, chờ 250 ms, ghi 0, chờ 250 ms. Code không cần dây ngoài và không áp cho ESP32-C6-DevKitC-1. Trước khi chạy trên board thật, kiểm đúng tên/PCB/firmware Pico non-W và cáp USB dữ liệu; lưu phiên bản MicroPython cùng log quan sát.</p>
<div class="table-wrap"><table><caption>Lịch lệnh lý tưởng, bỏ qua overhead MicroPython và sai số clock</caption><thead><tr><th>Thời điểm danh định</th><th>GP25 ra lệnh</th><th>LED kỳ vọng</th></tr></thead><tbody><tr><td>0 ms</td><td>1</td><td>Bật</td></tr><tr><td>250 ms</td><td>0</td><td>Tắt</td></tr><tr><td>500 ms</td><td>1</td><td>Bật</td></tr><tr><td>750 ms</td><td>0</td><td>Tắt</td></tr></tbody></table></div>
<p>Chu kỳ danh định <code>T=250+250=500 ms</code>, <code>f=1/T=2 Hz</code>, duty high <code>250/500=50%</code>. Thời điểm thực có overhead và jitter; LED mắt thường chỉ cho biết hiện tượng, không xác nhận đúng 250 ms. GP25 điều khiển LED trên board nhưng không xuất ra header Pico; không hướng dẫn cắm probe vào một pin header không tồn tại.</p>
<h2>3. Hai đường kiểm khác nhau</h2>
<div class="callout callout-practice"><div class="callout-header">🔬 Lab tái lập có điều kiện</div><ol><li>Không có board: chạy <code>python tools/verify_phase9_pico_lab.py</code>. Fake Pin kiểm thứ tự init-low, high/sleep, low/sleep và tính lịch 250/250 ms; đây là kiểm phần mềm, không là mô phỏng điện RP2040.</li><li>Có Pico non-W đúng revision/firmware: chép file lab thành <code>main.py</code> trên MicroPython board, reset và quan sát LED tích hợp. Ghi mã board, PCB marking, bản firmware, nguồn USB và trạng thái LED. Nếu cần số đo timing, dùng phương án đầu dò quang hoặc test point hợp lệ đã được reviewer duyệt; chưa có phép đo này.</li><li>Đổi <code>high_ms=100</code>, <code>low_ms=400</code> trong hàm gọi để dự đoán tần số/duty; kiểm lại trên host trước khi nạp board.</li></ol></div>
<div class="callout callout-warning"><div class="callout-header">⚠️ Không suy pinout giữa board</div><p>Pico W LED đi qua wireless chip; DevKitC v1.2 có RGB LED kiểu addressable ở GPIO8, không điều khiển bằng cùng một lệnh <code>Pin(25)</code>. Không có compile/nạp/đo board trong bản QA hiện tại. Phần định thời timer/IRQ/DMA chỉ được giải thích kiến trúc, chưa dùng ở lab này.</p></div>''',
        "exercise": "Đổi lab thành high <code>100 ms</code>, low <code>400 ms</code>. Tính T, f và duty high danh định; mô tả mức ở bốn mốc 0/100/500/600 ms. Nếu host fake Pin PASS, điều gì còn chưa được chứng minh trên Pico thật? Có được chép cùng lệnh GP25 sang Pico W không?",
        "answer": "<ol><li>1 điểm: <code>T=100+400=500 ms</code>.</li><li>1 điểm: <code>f=2 Hz</code>, duty high <code>100/500=20%</code>.</li><li>1 điểm: 0 high, 100 low, 500 high, 600 low trong lịch lý tưởng.</li><li>1 điểm: fake Pin chỉ kiểm trình tự phần mềm, chưa xác nhận firmware/điện áp/LED/jitter/clock trên board.</li><li>1 điểm: Pico W LED qua WL_GPIO0, không áp thẳng mã GP25; phải dùng đúng board API/mapping.</li></ol>",
        "checks": ["Tôi ghi đúng board non-W và GP25 LED tích hợp", "Tôi phân biệt tần số danh định với số đo", "Tôi không gán host fake là kiểm phần cứng"],
    },
    {
        "id": "a24", "title": "So Board Theo Mã & Revision", "subtitle": "Pico non-W và ESP32-C6-DevKitC-1 v1.2 giải những yêu cầu khác nhau; pinout và schematic cần đúng PCB/batch.",
        "base": "A22, A23", "units": "4", "figure_alt": "Hai thẻ so sánh board: Raspberry Pi Pico non-W tham chiếu board Rev3 dùng RP2040, LED GP25 và không có radio; ESP32-C6-DevKitC-1 v1.2 dùng module WROOM-1 hoặc WROOM-1U, RGB LED GPIO8 và radio Wi-Fi BLE 802.15.4.",
        "figure_text": "Bảng quyết định cấp board, không vẽ hai mạch LED tương đương. “Rev3” là hình board tham khảo của datasheet Pico; v1.2 là user guide DevKitC, schematic theo PW batch.",
        "source": f'<a href="{PICO_DOC}" target="_blank" rel="noopener">Raspberry Pi Pico board docs</a> và <a href="{ESP_BOARD}" target="_blank" rel="noopener">Espressif DevKitC-1 v1.2 user guide</a>',
        "transcript": "Bên trái là Pico đời đầu không W: chip RP2040, flash 2 MB trên board, LED đơn do GP25 điều khiển và không có radio tích hợp. Bên phải là ESP32-C6-DevKitC-1 v1.2: module WROOM-1 hoặc WROOM-1U với flash 8 MB, radio Wi-Fi/BLE/802.15.4 và RGB LED addressable gắn GPIO8. Các thông tin này không tạo pinout thay thế cho nhau.",
        "objectives": ["So hai board bằng đúng model/revision, phân biệt thông số chip/module với những gì board đưa ra.", "Chọn ứng viên cho bài LED offline hoặc logger không dây bằng yêu cầu và nguồn hãng.", "Nêu ít nhất ba thứ phải xác minh trên PCB/batch trước khi nối cảm biến và đánh giá nguồn/ADC."],
        "body": f'''
<h2>1. So ở cùng cấp board</h2>
<p><a href="{PICO_DOC}" target="_blank" rel="noopener">Raspberry Pi Pico</a> đời đầu không W dùng RP2040: hai Cortex-M0+, 264 kB SRAM chip, 2 MB flash board, 26 GPIO đa chức năng ở board; LED tích hợp trên GP25. Datasheet Pico Fig. 1 dùng ảnh <strong>Rev3</strong>, nhưng dự án chưa có board thực để kiểm marking. <a href="{ESP_BOARD}" target="_blank" rel="noopener">Espressif ESP32-C6-DevKitC-1 v1.2</a> có module WROOM-1 hoặc WROOM-1U, flash 8 MB trong module, Wi-Fi 6 2,4 GHz/Bluetooth LE/IEEE 802.15.4 và RGB LED addressable qua GPIO8. <a href="{ESP_CHIP}" target="_blank" rel="noopener">ESP32-C6 datasheet v1.5</a> ghi HP CPU RISC-V tối đa 160 MHz và LP CPU riêng; không lấy tần số tối đa làm tốc độ ứng dụng đã đo.</p>
<div class="table-wrap"><table><caption>Hai ứng viên ở đúng model tham khảo, chưa có board được mua/đo</caption><thead><tr><th>Tiêu chí</th><th>Pico đời đầu non-W, hình Rev3</th><th>ESP32-C6-DevKitC-1 v1.2</th></tr></thead><tbody><tr><td>Chip/module</td><td>RP2040 trên board</td><td>ESP32-C6-WROOM-1(U), module trong DevKitC</td></tr><tr><td>CPU</td><td>Hai Cortex-M0+</td><td>HP RISC-V tối đa 160 MHz; LP CPU riêng</td></tr><tr><td>Nhớ dùng làm ví dụ</td><td>264 kB SRAM chip, 2 MB flash board</td><td>8 MB SPI flash trong module; không suy heap từ con số này</td></tr><tr><td>Radio tích hợp</td><td>Không (bản non-W)</td><td>Wi-Fi 6/BLE/802.15.4</td></tr><tr><td>LED trên board</td><td>LED đơn GP25</td><td>RGB addressable do GPIO8 điều khiển</td></tr><tr><td>Cần kiểm khi nhận board</td><td>PCB/biến thể Pico vs W/H/2</td><td>v1.2, WROOM-1 hay -1U, PW batch/schematic v1.2/1.3/1.4</td></tr></tbody></table></div>
<h2>2. Chọn theo yêu cầu thay vì số lớn nhất</h2>
<p>Nếu mục tiêu là lab GPIO LED offline không dây ngoài, Pico non-W cho đường học ngắn: <a href="../labs/pico_gpio_blink.py">mã A23</a> nhắm đúng GP25. Nếu bài toán <strong>cần radio</strong> Wi-Fi/BLE/802.15.4, DevKitC v1.2 là ứng viên vì tài liệu board xác nhận radio. Nhưng không chuyển <code>Pin(25)</code> của Pico sang DevKitC: GPIO8 điều khiển một <em>RGB LED addressable</em>, giao thức và firmware khác; GPIO8 còn là strapping pin theo footnote bảng J1, nên mọi mạch ngoài trên chân đó cần đọc chế độ boot. Không dùng số “26 GPIO” của Pico để suy số GPIO lộ ở header DevKitC.</p>
<h2>3. Revision của schematic quan trọng</h2>
<p>Espressif user guide v1.2 ghi R29/R6 trong mạch LED được đổi ở lô sau PW-2023-07-0440 và R7 UART_RXD được đổi ở lô sau các mã PW năm 2024; tương ứng schematic v1.2/v1.3/v1.4. Một tên board v1.2 không đủ để chốt mọi điện trở trên PCB. Hướng chọn nguồn/GPIO/ADC của đồ án cần ảnh board, marking module, PW batch nếu có, schematic tương ứng và datasheet chip; chưa có nên không công bố dòng GPIO, sai số ADC hay ngân sách nguồn số cụ thể cho một bản board của học viên.</p>
<h2>4. Hoạt động quyết định</h2>
<div class="callout callout-practice"><div class="callout-header">🔬 Bảng chọn có thể kiểm</div><p>Tạo hai hàng yêu cầu: (a) LED tích hợp offline, (b) logger cần truyền không dây. Điền board ứng viên và nguồn hãng cho từng quyết định. Với (b), ghi thêm ba mục cần xác minh trước khi lắp cảm biến: đúng PCB/PW batch-schematic, module/anten, và nguồn/I/O của cảm biến so với board. Nếu chỉ có tài liệu, đánh dấu “ứng viên”, không đánh dấu “đã chạy”.</p></div>
<div class="callout callout-warning"><div class="callout-header">⚠️ Cổng board thật</div><p>Không có board Pico/DevKitC trong môi trường QA, chưa chạy ESP-IDF/MicroPython trên board, chưa đo nguồn, radio, ADC hay chân LED. Board v1.2 thuộc một họ có nhiều schematic revision theo batch; thiết kế dây nối phải dùng bản chính xác của mẫu thật.</p></div>''',
        "exercise": "Một logger cần gửi dữ liệu không dây và hiển thị trạng thái. Trong hai board của bảng, chọn ứng viên có nguồn hãng chứng minh radio. Liệt kê ít nhất ba thông tin revision/hardware phải kiểm trước khi nối một cảm biến analog. Có thể dùng nguyên lab <code>Pin(25)</code> của A23 để điều khiển RGB LED board này không?",
        "answer": "<ol><li>1 điểm: ESP32-C6-DevKitC-1 v1.2 là ứng viên vì guide board nêu Wi-Fi/BLE/802.15.4; chưa là board đã duyệt cho toàn hệ.</li><li>1 điểm: kiểm đúng model v1.2, WROOM-1 hay -1U và marking/batch PW để lấy schematic v1.2/1.3/1.4 tương ứng.</li><li>1 điểm: kiểm header/pin ADC, dải điện áp nguồn/cảm biến và đặc tính ADC theo datasheet chip đúng revision/batch; không suy từ tên họ.</li><li>1 điểm: không dùng nguyên <code>Pin(25)</code>; DevKitC có RGB addressable ở GPIO8, đồng thời GPIO8 là strapping pin, cần firmware/giao thức/schematic riêng.</li></ol>",
        "checks": ["Tôi trích dẫn tài liệu board cụ thể", "Tôi tách flash module khỏi SRAM chip", "Tôi kiểm schematic/PW batch trước khi quyết định dây"],
    },
]


FIGURES = {
    "a22": '''<rect x="35" y="82" width="830" height="316" rx="16" fill="#1e293b"/><rect x="55" y="110" width="600" height="270" rx="14" fill="#0f172a" stroke="#93c5fd" stroke-width="3"/><text x="78" y="140" fill="#93c5fd" font-size="20" font-family="Arial">RP2040 · ranh giới chip</text><g stroke="#93c5fd" stroke-width="4" fill="none"><path d="M140 215V245H200V266 M286 215V266 M375 293H400V190H426 M375 304H426 M375 277H395V235H665V244H680"/></g><rect x="82" y="160" width="115" height="55" rx="8" fill="#1d4ed8"/><rect x="230" y="160" width="115" height="55" rx="8" fill="#1d4ed8"/><rect x="162" y="266" width="213" height="70" rx="8" fill="#164e63"/><rect x="426" y="160" width="205" height="62" rx="8" fill="#14532d"/><rect x="426" y="269" width="205" height="70" rx="8" fill="#155e75"/><rect x="680" y="209" width="165" height="86" rx="8" fill="#713f12"/><g fill="white" font-family="Arial" font-size="18"><text x="100" y="194">CPU 0</text><text x="248" y="194">CPU 1</text><text x="186" y="308">Bus fabric</text><text x="445" y="196">SRAM 264 kB</text><text x="443" y="300">GPIO / ADC</text><text x="443" y="323">timer · chip</text><text x="695" y="245">QSPI flash</text><text x="695" y="271">2 MB · board</text></g><text x="682" y="333" fill="#cbd5e1" font-family="Arial" font-size="17">ngoài RP2040</text>''',
    "a23": '''<rect x="36" y="78" width="828" height="320" rx="16" fill="#1e293b"/><rect x="70" y="121" width="330" height="95" rx="12" fill="#0f172a" stroke="#93c5fd" stroke-width="3"/><text x="91" y="159" fill="white" font-family="Arial" font-size="21">Pico non-W · RP2040</text><text x="91" y="192" fill="#93c5fd" font-family="Arial" font-size="20">GP25 → LED on-board</text><text x="485" y="130" fill="#cbd5e1" font-family="Arial" font-size="20">Lịch lệnh danh định</text><path d="M485 268V184H565V268H645V184H725V268H805" fill="none" stroke="#86efac" stroke-width="5"/><path d="M480 275H820" stroke="#cbd5e1" stroke-width="2"/><g fill="#e2e8f0" font-family="Arial" font-size="18"><text x="475" y="307">0</text><text x="548" y="307">250</text><text x="631" y="307">500</text><text x="711" y="307">750</text><text x="782" y="307">1000 ms</text><text x="70" y="293">high 250 ms + low 250 ms</text><text x="70" y="326">T danh định = 500 ms · f ≈ 2 Hz</text></g>''',
    "a24": '''<rect x="35" y="80" width="395" height="316" rx="16" fill="#1e293b"/><rect x="470" y="80" width="395" height="316" rx="16" fill="#1e293b"/><g fill="#93c5fd" font-family="Arial" font-size="23"><text x="60" y="125">Pico non-W · tham chiếu Rev3</text><text x="494" y="125">ESP32-C6-DevKitC-1 v1.2</text></g><g fill="white" font-family="Arial" font-size="20"><text x="62" y="180">RP2040 · 264 kB SRAM</text><text x="62" y="224">2 MB flash trên board</text><text x="62" y="268">LED đơn GP25</text><text x="62" y="312">Không radio tích hợp</text><text x="495" y="180">WROOM-1(U) · 8 MB flash</text><text x="495" y="224">Wi-Fi / BLE / 802.15.4</text><text x="495" y="268">RGB addressable · GPIO8</text><text x="495" y="312">Schematic theo PW batch</text></g><text x="172" y="422" fill="#cbd5e1" font-family="Arial" font-size="18">Model và revision thật phải được kiểm trước khi lắp</text>''',
}


def svg(lesson: dict[str, object]) -> str:
    lesson_id = str(lesson["id"])
    title = str(lesson["title"])
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="900" height="480" viewBox="0 0 900 480" role="img" aria-labelledby="title desc"><title id="title">{lesson_id.upper()} — {escape(title)}</title><desc id="desc">{escape(str(lesson['figure_alt']))}</desc><rect width="900" height="480" rx="24" fill="#0f172a"/><text x="36" y="48" fill="#e2e8f0" font-family="Arial,sans-serif" font-size="25" font-weight="700">{lesson_id.upper()} · {escape(title)}</text>{FIGURES[lesson_id]}<text x="36" y="450" fill="#cbd5e1" font-family="Arial,sans-serif" font-size="17">Mô hình học tập · nguồn/giới hạn tại caption bài học</text></svg>\n'''


def render(lesson: dict[str, object], index: int) -> str:
    lesson_id = str(lesson["id"])
    title = str(lesson["title"])
    prev_id = f"a{21 + index:02}"
    prev_title = "FSM, Clock & Kiểm Timing" if index == 0 else str(LESSONS[index - 1]["title"])
    next_nav = (f'<a href="a{23 + index:02}.html" class="lesson-nav-btn"><div><div class="nav-label">Bài tiếp →</div><div class="nav-title">A{23 + index:02}: {escape(str(LESSONS[index + 1]["title"]))}</div></div></a>' if index < len(LESSONS) - 1 else "")
    objectives = "".join(f"<li>{item}</li>" for item in lesson["objectives"])
    checks = "".join(f'<div class="checklist-item"><input type="checkbox" id="{lesson_id}c{i}"><label for="{lesson_id}c{i}">{escape(item)}</label></div>' for i, item in enumerate(lesson["checks"], 1))
    return f'''<!DOCTYPE html>
<html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>{lesson_id.upper()}: {escape(title)} — Giáo Trình Điện Tử Thực Hành</title><meta name="description" content="{escape(str(lesson['subtitle']))}"><link rel="stylesheet" href="../assets/css/style.css"></head>
<body><header class="site-header"><a href="../index.html" class="logo"><div class="logo-icon">⚡</div><div><div class="logo-text">Điện Tử Thực Hành</div><div class="logo-sub">Giáo trình nâng cao</div></div></a><button class="btn-menu" aria-label="Menu"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button><nav class="header-nav"><a href="../index.html">Trang chủ</a><a href="../week4/day25.html">Bài nền D25</a></nav><div class="header-progress"><span class="progress-label">Lộ trình nâng cao · {lesson_id.upper()}</span></div></header>
<div class="app-layout"><aside class="sidebar" id="sidebar"></aside><main class="main-content"><article class="content-area"><div class="lesson-header"><div class="lesson-meta"><span class="tag tag-week">Phase 9</span><span class="tag tag-day">{lesson_id.upper()}</span><span class="tag tag-difficulty-beginner">M1 · {lesson['units']} ĐV</span></div><h1 class="lesson-title">{escape(title)}</h1><p class="lesson-subtitle">{escape(str(lesson['subtitle']))}</p><div class="lesson-stats"><span class="lesson-stat">⏱ {lesson['units']} ĐV đọc/bảng/bài tập</span><span class="lesson-stat">📚 Tiên quyết: {escape(str(lesson['base']))}</span></div></div>
<div class="objectives-box"><div class="objectives-title">🎯 Mục tiêu kiểm được</div><ul class="objectives-list">{objectives}</ul></div><figure class="figure figure--overview"><div class="figure-scroll" tabindex="0" role="region" aria-label="Sơ đồ có thể cuộn ngang"><img src="../assets/images/advanced/{lesson_id}.svg" width="900" height="480" loading="lazy" decoding="async" alt="{escape(str(lesson['figure_alt']))}"></div><figcaption class="figure-caption"><div class="figure-number">{lesson_id.upper()}-1 — {escape(title)}</div><div class="figure-text">{lesson['figure_text']}</div><div class="figure-source">Hình tự vẽ; đối chiếu {lesson['source']}. <a href="../assets/images/advanced/{lesson_id}.svg" target="_blank" rel="noopener">Mở hình lớn</a>.</div></figcaption></figure><details class="summary-transcript"><summary>Đọc hình bằng chữ</summary><p>{lesson['transcript']}</p></details>
{lesson['body']}
<div class="section-divider"><span class="section-divider-label">Bài tập độc lập</span></div><div class="exercise-section"><div class="exercise-title">📝 Tự giải trước khi xem đáp án</div><p>{lesson['exercise']}</p><div class="answer-section"><button class="answer-toggle">👁 Xem lời giải và rubric</button><div class="answer-content">{lesson['answer']}</div></div></div><div class="checklist"><div class="checklist-title">✅ Tự kiểm {lesson_id.upper()}</div>{checks}</div><div class="lesson-nav"><a href="{prev_id}.html" class="lesson-nav-btn"><div><div class="nav-label">← Bài trước</div><div class="nav-title">{prev_id.upper()}: {escape(prev_title)}</div></div></a>{next_nav}</div></article></main></div><script src="../assets/js/sidebar-data.js"></script><script src="../assets/js/main.js"></script><script>renderSidebar('{lesson_id}.html');</script></body></html>
'''


def main() -> None:
    for index, lesson in enumerate(LESSONS):
        lesson_id = str(lesson["id"])
        (ROOT / "advanced" / f"{lesson_id}.html").write_text(render(lesson, index), encoding="utf-8")
        (ROOT / "assets/images/advanced" / f"{lesson_id}.svg").write_text(svg(lesson), encoding="utf-8")
        print(f"Wrote {lesson_id}.html and {lesson_id}.svg")


if __name__ == "__main__":
    main()
