"""Author P9-03 A25–A28 with vendor-scoped sensor examples."""

from __future__ import annotations

import build_phase9_board_lessons as board

TMP = "https://www.analog.com/media/en/technical-documentation/data-sheets/tmp35_36_37.pdf"
DS = "https://www.analog.com/media/en/technical-documentation/data-sheets/ds18b20.pdf"
OPT = "https://www.ti.com/lit/ds/symlink/opt3001.pdf"
HALL = "https://www.ti.com/lit/ds/symlink/drv5032.pdf"
BMP = "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds001.pdf"
IMU = "https://www.st.com/resource/en/datasheet/lsm6dsox.pdf"
TOF = "https://www.st.com/resource/en/datasheet/vl53l1x.pdf"


def link(url: str, label: str) -> str:
    return f'<a href="{url}" target="_blank" rel="noopener">{label}</a>'


LESSONS = [
    {
        "id": "a25", "title": "Bản Đồ Cảm Biến Theo Đại Lượng", "subtitle": "Đọc đúng part, đơn vị, điều kiện thử và kiểu I/O trước khi chọn cảm biến.",
        "base": "A08, D27, D40", "units": "5",
        "figure_alt": "Bản đồ bảy part cảm biến: TMP36/DS18B20 nhiệt độ, OPT3001 ánh sáng, DRV5032 từ trường, BMP280 áp suất, LSM6DSOX chuyển động, VL53L1X khoảng cách; mỗi nhánh có dạng I/O.",
        "figure_text": "Các nhánh là phân loại chức năng, không phải sơ đồ nối dây. Thông số cụ thể và điều kiện đo nằm ở bảng A25; mọi module/breakout cần tài liệu riêng.",
        "source": ", ".join([link(TMP, "ADI TMP36 Rev. H"), link(DS, "ADI DS18B20 Rev. 6"), link(OPT, "TI OPT3001 Rev. C"), link(HALL, "TI DRV5032 Rev. H"), link(BMP, "Bosch BMP280"), link(IMU, "ST LSM6DSOX"), link(TOF, "ST VL53L1X Rev. 8")]),
        "transcript": "Nhiệt độ có TMP36 xuất điện áp analog và DS18B20 dùng bus 1-Wire. Ánh sáng OPT3001 xuất kết quả lux qua I²C. DRV5032 là công tắc Hall báo ngưỡng từ trường bằng mức số. BMP280 đo áp suất khí quyển bằng I²C/SPI. LSM6DSOX cho gia tốc và tốc độ góc. VL53L1X đo khoảng cách bằng thời gian bay quang học qua I²C. Các đường là nhóm dữ liệu, không nối chung bảy chip.",
        "objectives": ["Lập ma trận đại lượng–nguyên lý–nguồn/I/O–dải–sai số/độ phân giải–đáp ứng cho bảy part thật.", "Phân biệt sai số với độ phân giải, thời gian đổi số với đáp ứng vật lý và silicon với breakout.", "Nêu ba việc phải xác nhận từ marking, package, board revision trước khi nối vào MCU."],
        "body": f'''
<h2>1. Bản đồ phải ghi điều kiện</h2>
<p>Bảng dưới dùng <strong>IC trần theo datasheet hãng</strong>, chưa chọn breakout hay nối với Pico. “Không có số chung” nghĩa là đặc tính phụ thuộc package/cấu hình/môi trường hoặc thiết bị chỉ báo ngưỡng; không được tự điền số chính xác. Dải đo không phải dải nguồn, và độ phân giải không là độ chính xác.</p>
<div class="table-wrap"><table><caption>Bảy ví dụ có thật; xem link datasheet ở từng hàng</caption><thead><tr><th>Đại lượng · part · nguyên lý</th><th>Nguồn và I/O</th><th>Dải/độ phân giải</th><th>Sai số và đáp ứng</th></tr></thead><tbody>
<tr><td>Nhiệt · {link(TMP, 'TMP36')} · điện áp phụ thuộc nhiệt</td><td>2,7–5,5 V; VOUT analog tới ADC phù hợp</td><td>−40…125 °C; 10 mV/°C danh định</td><td>±1 °C ở 25 °C, ±2 °C toàn dải là <em>typical</em>; đáp ứng nhiệt phụ thuộc package, PCB, môi trường. Thời bật điện 0,5–1 ms không là τ nhiệt.</td></tr>
<tr><td>Nhiệt · {link(DS, 'DS18B20')} · đo số tích hợp</td><td>VDD 3,0–5,5 V khi cấp riêng; 1-Wire</td><td>−55…125 °C; 12-bit LSB 0,0625 °C</td><td>±0,5 °C ở −10…85 °C theo bảng; đổi số 12-bit tối đa 750 ms, chưa gồm thời gian nhiệt/bus.</td></tr>
<tr><td>Ánh sáng · {link(OPT, 'OPT3001')} · quang điện/lọc phổ</td><td>VDD 1,6–3,6 V; I²C, điện trở kéo lên theo miền I/O</td><td>Đến 83.865,6 lux full-scale; LSB 0,01 lux chỉ ở range thấp nhất</td><td>Phụ thuộc phổ/góc/cover glass; 100 hoặc 800 ms tích phân, auto-range có thể kéo dài.</td></tr>
<tr><td>Từ · {link(HALL, 'DRV5032')} · Hall switch</td><td>VCC 1,65–5,5 V; mức số open-drain hoặc push-pull theo mã</td><td>Ngưỡng BOP/BRP theo hậu tố part; không xuất trị số mT liên tục</td><td>Sai số là khoảng ngưỡng/hysteresis theo mã; phiên bản lấy mẫu 5/20/80 Hz, không là latency bảo đảm của mọi mã.</td></tr>
<tr><td>Áp suất · {link(BMP, 'BMP280')} · màng piezoresistive</td><td>VDD 1,71–3,6 V; VDDIO 1,2–3,6 V; I²C/SPI</td><td>300–1100 hPa; độ phân giải output 0,0016 hPa ở mode ultra-high-resolution</td><td>Absolute accuracy <em>typical</em> ±1 hPa ở 950–1050 hPa, 0…40 °C; thời đo <em>typical</em> 5,5 ms ở preset ultra-low-power.</td></tr>
<tr><td>Chuyển động · {link(IMU, 'LSM6DSOX')} · MEMS gia tốc/con quay</td><td>Analog supply 1,71–3,6 V; I²C/SPI/I3C theo mode</td><td>Gia tốc ±2/4/8/16 g; góc ±125/250/500/1000/2000 dps; sensitivity typical 0,061 mg/LSB tại ±2 g</td><td>Bias/noise còn riêng; ODR chọn theo mode (ví dụ 104 Hz), không phải độ trễ toàn hệ hay accuracy vị trí.</td></tr>
<tr><td>Khoảng cách · {link(TOF, 'VL53L1X')} · time of flight</td><td>AVDD 2,6–3,5 V; I²C; I/O mặc định 1,8 V, mode 2,8 V cần cấu hình</td><td>Đảm bảo từ 4 cm; tới 4 m chỉ trong điều kiện mục tiêu/ánh sáng/timing thích hợp</td><td>Sai số phụ thuộc phản xạ, môi trường, cover glass; bảng thử hãng dùng timing budget 100 ms hoặc giá trị khác theo mode.</td></tr>
</tbody></table></div>
<h2>2. Bài chọn nguồn và nhận diện</h2>
<p>Đọc top marking, mã đặt hàng, package và revision board; mở pin configuration đúng <em>góc nhìn</em> trên datasheet. Ví dụ hình pin TO-92 của TMP36 nhìn <em>từ đáy</em>; không đổi nó thành mặt trước. Với DRV5032, hậu tố xác định ngưỡng, tần số lấy mẫu và output driver. Với VL53L1X trần, I²C mặc định 1,8 V: chưa xác định breakout/level shifter thì không nối thẳng bus 3,3 V của Pico. Datasheet silicon không chứng minh module bán lẻ có mạch chuyển mức hay regulator.</p>
<div class="callout callout-practice"><div class="callout-header">🔬 Thực hành giấy</div><p>Chọn cảm biến đo nhiệt độ phòng và cảm biến phát hiện nam châm. Ghi đại lượng, unit, mã part/suffix/package, dải đo, supply/I/O, loại output, thông số sai số/độ phân giải, thời gian liên quan và từng điều kiện. Khoanh những ô phải đọc thêm khi biết PCB/module thực tế. Không vẽ chân header từ bảng IC trần.</p></div>
<div class="callout callout-warning"><div class="callout-header">⚠️ Cổng vật lý</div><p>Chưa có part/board/mã đặt hàng/breakout được kiểm. Bảng là hồ sơ học tập theo datasheet, không phải wiring/BOM đã duyệt. Bài A26–A27 phân tích trường hợp; P9-04 mới chọn một đường lab cụ thể.</p></div>''',
        "exercise": "Chọn TMP36 và DRV5032 từ bảng. Với mỗi part, nêu đại lượng, dạng output, nguồn, ‘độ phân giải hay ngưỡng’, yếu tố đáp ứng và ít nhất một điều chưa được phép suy về pinout/module. Vì sao không thể lấy 0,01 lux của OPT3001 làm độ chính xác?",
        "answer": "<ol><li>1 điểm: TMP36 đo nhiệt bằng VOUT analog, 2,7–5,5 V, 10 mV/°C danh định; đáp ứng nhiệt phụ thuộc package/PCB/môi trường.</li><li>1 điểm: DRV5032 phát hiện ngưỡng từ trường qua output số; VCC 1,65–5,5 V, BOP/BRP và nhịp lấy mẫu phụ thuộc suffix, không có ‘độ phân giải mT’ của phép đo liên tục.</li><li>1 điểm: pinout TMP36 tùy package/góc nhìn và DRV5032 tùy suffix; chưa suy module có regulator/level shifter.</li><li>1 điểm: 0,01 lux là LSB ở range thấp nhất của OPT3001, trong khi sai số chịu phổ/góc/cover glass và điều kiện đo.</li></ol>",
        "checks": ["Tôi ghi điều kiện của số datasheet", "Tôi tách part trần với module", "Tôi không đồng nhất LSB và accuracy"],
    },
    {
        "id": "a26", "title": "Cảm Biến Nhiệt, Ánh Sáng & Từ", "subtitle": "So công nghệ analog, bus số và công tắc ngưỡng theo câu hỏi đo cụ thể.",
        "base": "A25", "units": "5",
        "figure_alt": "Bảng chọn có ba nhánh: nhiệt TMP36 analog so DS18B20 1-Wire; ánh sáng OPT3001 I²C so LDR chia áp; từ DRV5032 Hall switch so reed switch; bên dưới là cổng supply và thời gian.",
        "figure_text": "So sánh công nghệ theo đầu ra và sai số cần quản lý; LDR/reed là họ công nghệ đối chiếu, không phải part đã có BOM hay trị số để lắp.",
        "source": f'{link(TMP,"ADI TMP36 Rev. H")}, {link(DS,"ADI DS18B20 Rev. 6")}, {link(OPT,"TI OPT3001 Rev. C")}, {link(HALL,"TI DRV5032 Rev. H")}',
        "transcript": "Nhánh nhiệt đặt TMP36 analog cạnh DS18B20 bus số. Nhánh ánh sáng đặt cảm biến lux OPT3001 cạnh LDR điện trở phụ thuộc ánh sáng. Nhánh từ đặt Hall switch DRV5032 cạnh reed switch cơ khí. Mỗi cặp khác nhau ở đại lượng đầu ra, giao tiếp, hiệu chuẩn và thời gian; không có wiring chung cho sáu lựa chọn.",
        "objectives": ["Tính nhiệt từ VOUT TMP36 và giải thích sai số ADC khác sai số sensor.", "So TMP36 với DS18B20 theo nguồn, output, dải, sai số và thời gian chuyển đổi.", "Chọn công nghệ ánh sáng/từ theo yêu cầu lux liên tục hay phát hiện ngưỡng."],
        "body": f'''
<h2>1. Nhiệt độ: điện áp so với 1-Wire</h2>
<p>{link(TMP,'TMP36 Rev. H')} cho 750 mV tại 25 °C và slope 10 mV/°C, vì vậy mô hình danh định <code>T[°C]=(VOUT[mV]−500)/10</code>. Nếu đọc 760 mV thì <code>T=26 °C</code> danh định. Đây chưa tính sai số sensor, ADC, reference, loading và nhiệt tiếp xúc. ±1 °C ở 25 °C và ±2 °C trên −40…125 °C trong phần giới thiệu là <em>typical</em>, không phải bảo đảm mọi mẫu/grade; đọc bảng grade F/G cho giới hạn khi chốt BOM. Thời bật điện 0,5–1 ms không phải đáp ứng nhiệt của package.</p>
<p>{link(DS,'DS18B20 Rev. 6')} đưa nhiệt độ qua 1-Wire, VDD 3,0–5,5 V khi cấp riêng; đo −55…125 °C, ±0,5 °C trong −10…85 °C, cấu hình 9–12 bit. Ở 12 bit, LSB 0,0625 °C nhưng phép chuyển đổi có thể tới 750 ms. Giá trị thanh ghi +85 °C sau bật nguồn có thể là giá trị khởi đầu: phát Convert T, chờ hoàn thành, đọc scratchpad và CRC trước khi dùng. Parasite power cần strong pull-up theo datasheet; bài này chọn cấp VDD riêng khi so, không giả vẽ bus.</p>
<div class="table-wrap"><table><caption>Chọn theo điều kiện, không theo chữ “digital chính xác hơn”</caption><thead><tr><th>Tình huống</th><th>Ứng viên và lý do</th><th>Điều cần kiểm</th></tr></thead><tbody><tr><td>Đã có ADC phù hợp, cần quan sát tín hiệu VOUT liên tục</td><td>TMP36</td><td>Reference/LSB/độ tuyến tính ADC, package/thermal coupling</td></tr><tr><td>Cần nhiều điểm nhiệt trên một bus với ID</td><td>DS18B20</td><td>1-Wire timing/pull-up/CRC, thời chuyển đổi, chân pinout đúng package</td></tr><tr><td>Yêu cầu chu kỳ cập nhật dưới 500 ms ở 12 bit</td><td>Không chốt DS18B20 12-bit chỉ từ số 750 ms max</td><td>Xét độ phân giải khác hoặc part khác; kiểm cả đáp ứng nhiệt thực</td></tr></tbody></table></div>
<h2>2. Ánh sáng: lux so với điện trở phụ thuộc sáng</h2>
<p>{link(OPT,'OPT3001 Rev. C')} là cảm biến ánh sáng môi trường đưa mã lux qua I²C, VDD 1,6–3,6 V. Full-scale lớn nhất 83.865,6 lux; 0,01 lux/LSB chỉ khi đặt range thấp nhất, trong khi range cao có LSB lớn hơn. Chế độ tích phân 100/800 ms đánh đổi tốc độ và độ phân giải hiệu dụng; auto-range có thể cần phép đánh giá lại. Không coi chỉ số 0,01 lux là sai số phép đo qua kính che hoặc dưới mọi phổ/góc.</p>
<p>LDR là điện trở thay đổi theo chiếu sáng, có thể tạo cầu chia áp và ADC như A02/D27; nếu cần <em>mức lux có truy xuất</em>, phải chọn mã LDR, đường R–lux, phổ, nhiệt và hiệu chuẩn riêng. Chưa chọn part LDR nên không gán dải/sai số/thời gian cho nó. Nếu chỉ cần ngưỡng sáng/tối, LDR + comparator có thể là ứng viên; nếu cần lux số và điều kiện quang học được công bố, OPT3001 có đường datasheet rõ hơn.</p>
<h2>3. Từ trường: phát hiện ngưỡng so với tiếp điểm</h2>
<p>{link(HALL,'DRV5032 Rev. H')} là Hall switch lấy mẫu, VCC 1,65–5,5 V. BOP/BRP, cực từ, nhịp 5/20/80 Hz và kiểu push-pull/open-drain tùy <strong>suffix</strong>. Nó phát mức số khi vượt ngưỡng, không đo biên độ mT liên tục. Reed switch là tiếp điểm cơ khí đóng/mở bởi nam châm; có thể phù hợp bài chỉ cần phát hiện tiếp cận nhưng cần kiểm bounce, tuổi thọ, hướng/độ mạnh nam châm theo part. Không có mã reed đã chọn nên không khẳng định tốc độ hay tuổi thọ số. Với Hall open-drain cần nguồn kéo lên tương thích input MCU; với push-pull không thể mặc nhiên kéo lên 5 V rồi nối vào GPIO 3,3 V.</p>
<div class="callout callout-practice"><div class="callout-header">🔬 Bảng chọn</div><p>Viết ba yêu cầu: (1) nhiệt 20–40 °C, cập nhật ≤1 s; (2) báo “sáng/tối” hay lux tuyệt đối; (3) phát hiện nam châm đứng yên. Với mỗi yêu cầu chọn công nghệ, xác định output/nguồn/dải và chỉ ra phép thử/chứng cứ còn thiếu. Không đổi chữ “độ phân giải” thành “accuracy”.</p></div>''',
        "exercise": "TMP36 xuất 0,760 V: tính nhiệt danh định. DS18B20 12 bit có LSB 0,0625 °C và conversion tối đa 750 ms: hai số này chứng minh sai số ±0,0625 °C và chu kỳ dữ liệu mới 100 ms không? Chọn thiết bị cho phép đo lux số, nêu một yếu tố làm sai kết quả; Hall DRV5032 có đo biên độ mT liên tục không?",
        "answer": "<ol><li>1 điểm: (760−500)/10=26 °C danh định.</li><li>1 điểm: LSB 0,0625 °C chỉ là bước mã, không là accuracy; DS18B20 có giới hạn accuracy riêng ±0,5 °C trong −10…85 °C.</li><li>1 điểm: 750 ms max ở 12 bit không chứng minh cập nhật dữ liệu mới mỗi 100 ms; còn bus và nhiệt.</li><li>1 điểm: OPT3001 cho lux số, nhưng phổ/góc/kính che ảnh hưởng; DRV5032 là switch ngưỡng, không đo B liên tục.</li></ol>",
        "checks": ["Tôi tính đúng đơn vị mV/°C", "Tôi kiểm CRC và dữ liệu khởi đầu", "Tôi phân biệt ngưỡng Hall với phép đo B"],
    },
    {
        "id": "a27", "title": "Áp Suất, Chuyển Động & Khoảng Cách", "subtitle": "Chọn sensor theo môi trường và đặc tính phép đo, không chỉ theo số dải lớn nhất.",
        "base": "A25", "units": "5",
        "figure_alt": "Ba thẻ BMP280 khí áp, LSM6DSOX IMU sáu trục và VL53L1X khoảng cách ToF, kèm đường dữ liệu I2C hoặc SPI và ba giới hạn: điều kiện độ chính xác, mode/ODR, phản xạ và mức I/O.",
        "figure_text": "Đường dữ liệu là khái niệm giao tiếp; không vẽ chung bus/đấu nguồn. VL53L1X mặc định I/O 1,8 V, phải xử lý miền điện áp theo thiết kế thật.",
        "source": f'{link(BMP,"Bosch BMP280")}, {link(IMU,"ST LSM6DSOX")}, {link(TOF,"ST VL53L1X Rev. 8")}',
        "transcript": "BMP280 đo áp suất không khí và có I²C hoặc SPI. LSM6DSOX có gia tốc kế ba trục và con quay ba trục, thông số tùy full-scale và output-data-rate. VL53L1X phát tia quang và đo thời gian bay để lấy khoảng cách, dùng I²C nhưng mức I/O mặc định 1,8 volt. Ba nhánh không chia sẻ dải hoặc sai số.",
        "objectives": ["Nêu dải, nguồn/I/O, độ phân giải/sai số và thời gian theo điều kiện của BMP280, LSM6DSOX, VL53L1X.", "So pressure sensor, IMU/PIR và ToF/siêu âm theo đại lượng thực sự quan sát.", "Nhận ra cổng điện áp I/O và điều kiện quang học có thể loại một lựa chọn."],
        "body": f'''
<h2>1. Áp suất: BMP280 đo khí quyển</h2>
<p>{link(BMP,'Bosch BMP280 datasheet Table 2/Table 13')} mô tả cảm biến áp suất tuyệt đối piezoresistive, dải 300–1100 hPa; VDD 1,71–3,6 V, VDDIO 1,2–3,6 V, I²C/SPI. Độ phân giải <em>output</em> 0,0016 hPa ở mode ultra-high-resolution <strong>không</strong> đồng nghĩa sai số ±0,0016 hPa. Absolute accuracy <em>typical</em> ±1 hPa chỉ trong 950–1050 hPa, 0…40 °C; relative accuracy ±0,12 hPa typical là điều kiện riêng 700–900 hPa ở 25 °C. Thời đo <em>typical</em> 5,5 ms thuộc preset ultra-low-power, không phải mọi cấu hình oversampling/filter. BMP280 không thay pressure transducer cho khí nén vượt 1100 hPa.</p>
<h2>2. Chuyển động: IMU đo kinematics, PIR phát hiện biến thiên hồng ngoại</h2>
<p>{link(IMU,'ST LSM6DSOX datasheet Table 2')} tích hợp gia tốc kế 3 trục và con quay 3 trục. Full-scale gia tốc chọn ±2/4/8/16 g, góc chọn ±125/250/500/1000/2000 dps, nguồn analog 1,71–3,6 V; giao tiếp I²C/SPI/I3C tùy mode. Ở ±2 g, sensitivity <em>typical</em> là 0,061 mg/LSB; chọn ODR 104 Hz là một cấu hình khả dĩ, không chứng minh độ trễ toàn hệ 1/104 s. Kết quả chịu bias/noise, hướng lắp và lọc; full-scale lớn giảm nguy cơ bão hòa nhưng có thể làm bước mã thô hơn. Datasheet không đưa một số “độ chính xác vị trí” có thể áp cho tích phân gia tốc mọi thời gian. PIR như ở D40 phát hiện biến thiên hồng ngoại của cảnh, không cho gia tốc/góc quay; muốn so thời gian trễ/tầm phát hiện phải chọn module và optics cụ thể, chưa có ở bài này.</p>
<h2>3. Khoảng cách: ToF so IR/siêu âm</h2>
<p>{link(TOF,'ST VL53L1X Rev. 8')} dùng time of flight, AVDD 2,6–3,5 V và I²C. Dải gần được bảo đảm từ 4 cm; con số đến 4 m phụ thuộc mục tiêu, độ phản xạ, ánh sáng, field of view và timing budget. Bảng hãng lấy ví dụ nominal 2,8 V/23 °C, long mode và budget 100 ms, không có kính che; thay cover glass hoặc mục tiêu tối phải đánh giá lại. Chip trần khởi đầu I/O 1,8 V; mode 2,8 V cần cấu hình, <strong>không coi SDA/SCL 3,3 V an toàn</strong> chỉ vì AVDD cho phép 3,5 V. Dùng breakout có level shifter chỉ khi tài liệu đúng board xác nhận. Laser Class 1 theo cấu hình hãng; không sửa optics/drive.</p>
<p>IR phản xạ đơn giản phụ thuộc reflectance mạnh; siêu âm phụ thuộc đường truyền âm, vật cản/biên dạng và môi trường. Đây là hai họ để sàng lọc, chưa có mã part nên chưa ghi dải hay “chính xác hơn ToF”. Với ứng dụng có mặt kính/ánh sáng ngoài trời, cần phép thử trên cụm cơ khí thật; với môi trường có bọt/khói/hơi nước, đường siêu âm cũng cần thử riêng.</p>
<div class="table-wrap"><table><caption>Chọn theo đại lượng, không hoán đổi output</caption><thead><tr><th>Yêu cầu</th><th>Ứng viên</th><th>Điều kiện loại trừ/chưa biết</th></tr></thead><tbody><tr><td>Áp suất khí quyển 950–1050 hPa, 0…40 °C</td><td>BMP280</td><td>Hiệu chuẩn hệ/độ cao và cấu hình oversampling</td></tr><tr><td>Gia tốc/góc quay thiết bị</td><td>LSM6DSOX</td><td>Full-scale/ODR/bias; PIR không thay IMU</td></tr><tr><td>Khoảng cách tới mục tiêu có đặc tính quang biết</td><td>VL53L1X</td><td>Reflectance/FoV/budget/cover glass, I/O level</td></tr></tbody></table></div>
<div class="callout callout-practice"><div class="callout-header">🔬 Phiếu loại trừ</div><p>Với ba nhu cầu trên, ghi dải, nguồn/I/O, độ phân giải hoặc giới hạn sai số đúng điều kiện, thời gian lấy mẫu/đo, bề mặt/môi trường và một phép thử trên cụm thật cần làm. Trước khi nối Pico 3,3 V với VL53L1X, ghi rõ sơ đồ level shifting hoặc breakout được chứng nhận; nếu chưa có, đánh dấu “không đấu”.</p></div>''',
        "exercise": "Một vật cần đo ở 3 m, bề mặt tối, dưới ánh sáng mạnh. Có thể cam kết VL53L1X sai số ±20 mm và cứ 100 ms có mẫu không? BMP280 có resolution output 0,0016 hPa ở mode ultra-high-resolution: có phải sai số tuyệt đối ±0,0016 hPa? Cần gia tốc/góc quay thì dùng PIR hay LSM6DSOX? GPIO I²C 3,3 V có đấu thẳng VL53L1X trần không?",
        "answer": "<ol><li>1 điểm: không cam kết 3 m ±20 mm hay 100 ms; reflectance/ambient/timing budget/FoV/cover glass và chế độ cần đối chiếu bảng hãng, thử thực.</li><li>1 điểm: 0,0016 hPa là resolution output ở mode ultra-high-resolution; absolute accuracy typical ±1 hPa chỉ ở 950–1050 hPa/0…40 °C.</li><li>1 điểm: LSM6DSOX cho gia tốc/góc quay; PIR chỉ báo biến thiên hồng ngoại.</li><li>1 điểm: không đấu thẳng I²C 3,3 V vào chip trần mặc định I/O 1,8 V; cần thiết kế chuyển mức/mode được chứng minh.</li></ol>",
        "checks": ["Tôi dùng accuracy đúng điều kiện", "Tôi không coi IMU là vị trí chính xác", "Tôi kiểm mức I/O trước khi nối"],
    },
    {
        "id": "a28", "title": "Sai Số, Hiệu Chuẩn & Lọc Cảm Biến", "subtitle": "Tách dữ liệu chuẩn, điểm fit và điểm kiểm độc lập trong một phép hiệu chuẩn có thể tính lại.",
        "base": "A25, A26, A27, D25", "units": "6",
        "figure_alt": "Đồ thị hiệu chuẩn TMP36 giả định với hai điểm fit 0 độ C ứng với 0,510 V và 50 độ C ứng với 1,005 V, điểm kiểm độc lập 25 độ C ứng với 0,762 V; đường danh định và đường hiệu chuẩn được phân biệt.",
        "figure_text": "Số đo <strong>giả lập trên giấy</strong>, chưa có TMP36 hoặc chuẩn nhiệt. Hai điểm fit xác định slope/offset; điểm 25 °C để kiểm, không dùng để fit.",
        "source": f'{link(TMP,"ADI TMP36 Rev. H — 750 mV tại 25 °C, 10 mV/°C danh định")}',
        "transcript": "Hai chấm dùng để fit là 0 độ C với 0,510 volt và 50 độ C với 1,005 volt. Đường qua hai chấm có độ dốc 9,9 milivolt mỗi độ C và intercept 0,510 volt. Chấm kiểm 25 độ C với 0,762 volt nằm lệch đường fit: dự đoán 25,4545 độ C, sai số cộng 0,4545 độ C. Đường danh định cho 26,2 độ C, sai số cộng 1,2 độ C. Mọi số chấm đều giả định.",
        "objectives": ["Từ bộ dữ liệu giả lập, fit hai điểm TMP36 và tính sai số trên điểm kiểm độc lập.", "Lập ngân sách sai số tách chuẩn, voltmeter/ADC, sensor, mô hình, môi trường và lượng tử hóa.", "Chọn lọc trung bình có giới hạn trễ, giữ raw data và không tuyên bố accuracy thật từ bài giấy."],
        "body": f'''
<h2>1. Nguồn và bộ dữ liệu</h2>
<p>{link(TMP,'ADI TMP36 Rev. H')} cho mô hình danh định 750 mV tại 25 °C và 10 mV/°C, nên <code>Vnom=0,500+0,010T</code> (V). Bảng sau là <strong>dữ liệu tổng hợp do bài học tạo ra</strong>, không phải số của một TMP36 đã mua hoặc từ datasheet. Giả định có chuẩn nhiệt độc lập và đồng hồ điện áp, nhưng thiết bị/uncertainty chưa được chọn. Hai đầu mút dùng để fit; 25 °C là điểm kiểm giữ riêng.</p>
<div class="table-wrap"><table><caption>Bộ dữ liệu tổng hợp, V tính bằng volt</caption><thead><tr><th>Vai trò</th><th>T chuẩn giả định</th><th>V đọc giả định</th><th>T danh định (V−0,500)/0,010</th></tr></thead><tbody><tr><td>Fit thấp</td><td>0 °C</td><td>0,510 V</td><td>1,0 °C</td></tr><tr><td>Kiểm độc lập</td><td>25 °C</td><td>0,762 V</td><td>26,2 °C</td></tr><tr><td>Fit cao</td><td>50 °C</td><td>1,005 V</td><td>50,5 °C</td></tr></tbody></table></div>
<h2>2. Fit và kiểm sai số</h2>
<p><code>b=(1,005−0,510)/(50−0)=0,0099 V/°C</code>; <code>a=0,510 V</code>; mô hình fit <code>V=a+bT</code>. Từ 0,762 V tại điểm giữ riêng: <code>Tfit=(0,762−0,510)/0,0099=25,4545… °C</code>. Sai số có dấu so với chuẩn giả định 25 °C là <code>+0,4545… °C</code>; trước fit là <code>26,2−25=+1,2 °C</code>. Sai số tuyệt đối trên <em>một điểm kiểm</em> giảm từ 1,2 xuống khoảng 0,455 °C, không chứng minh trên toàn dải hay trên phần cứng. Phần dư điện áp tại 25 °C so với đường fit là <code>0,762−(0,510+0,0099×25)=+0,0045 V</code>.</p>
<h2>3. Ngân sách sai số trước khi đo thật</h2>
<p>Ở 10 mV/°C danh định, <strong>nếu</strong> ADC/voltmeter có sai số ±2 mV trong điều kiện lắp, thành phần tương đương ±0,2 °C theo slope danh định. Đó là giả định bài tập, chưa là thông số ADC Pico hay DMM thật. Sai số TMP36 theo grade/nhiệt, sai số chuẩn nhiệt, điện áp tham chiếu, tải VOUT, tự gia nhiệt, tiếp xúc nhiệt, độ tuyến tính, lượng tử hóa và biến thiên môi trường phải được xét riêng. Không cộng tuyến tính giá trị typical như một worst-case bảo đảm; muốn khoảng tin cậy phải có phân bố/tương quan và phép hiệu chuẩn chuẩn truy xuất. Dữ liệu fit bị ảnh hưởng bởi sai số ở chính hai mốc chuẩn; kiểm 25 °C phải đo độc lập.</p>
<h2>4. Lọc và giao tiếp</h2>
<p>Với các mẫu số hóa <code>24,9; 25,4; 25,1 °C</code> (giả định), trung bình cộng là <code>25,133… °C</code>. Trung bình ba mẫu có thể giảm nhiễu ngẫu nhiên độc lập nhưng tạo trễ, không sửa bias offset hay lỗi cấp nguồn; xung thật có thể bị làm mờ. Giữ raw voltage/code, timestamp, nhiệt chuẩn, cấu hình ADC/reference, phiên bản công thức và giá trị đã lọc. Với sensor số, thêm CRC/status, mode và thời gian đổi số; chỉ đọc dữ liệu mới khi conversion ready. Không dùng bộ lọc để che lỗi bus hoặc chọn sai dải.</p>
<div class="callout callout-practice"><div class="callout-header">🔬 Phiếu phép đo tương lai</div><p>Ghi mã TMP36/package/grade và datasheet revision; mã board/ADC/reference; chuẩn nhiệt và bất định; trạng thái ổn định nhiệt; ba lần đọc raw mỗi điểm 0/25/50 °C; hai điểm fit, một điểm kiểm; sai số trước/sau cùng ngày và độ lặp. Nếu không có part và chuẩn, chỉ chạy <code>python tools/verify_phase9_sensors.py</code> để kiểm toán số học của dữ liệu tổng hợp.</p></div>
<div class="callout callout-warning"><div class="callout-header">⚠️ Giới hạn</div><p>Chưa thu dữ liệu từ cảm biến/thiết bị chuẩn thật và chưa chứng minh accuracy sau hiệu chuẩn. Giá trị typical trong datasheet không tự trở thành tiêu chí PASS trên một mẫu cụ thể; quyết định kỹ thuật cần mã đặt hàng, điều kiện thử và reviewer phần cứng.</p></div>''',
        "exercise": "Từ điểm fit (0 °C, 0,510 V) và (50 °C, 1,005 V), tính a,b. Với điểm kiểm độc lập (25 °C, 0,762 V), tính T và sai số trước/sau; nêu vì sao đây chưa là chứng nhận accuracy. Nếu sai số điện áp giả định ±2 mV, quy đổi xấp xỉ theo slope danh định. Tính trung bình 24,9/25,4/25,1 °C và một hạn chế của lọc.",
        "answer": "<ol><li>1 điểm: a=0,510 V và b=0,0099 V/°C.</li><li>1 điểm: Tfit=25,4545… °C, sai số +0,4545… °C; Tnom=26,2 °C, sai số +1,2 °C.</li><li>1 điểm: số là tổng hợp, chỉ một điểm giữ riêng; còn chuẩn/ADC/sensor/môi trường nên chưa chứng nhận accuracy thật.</li><li>1 điểm: ±2 mV/10 mV·°C⁻¹≈±0,2 °C dưới giả định slope danh định, không là spec Pico.</li><li>1 điểm: trung bình 25,133… °C; lọc có trễ và không sửa bias hệ thống.</li></ol>",
        "checks": ["Tôi giữ điểm kiểm ngoài phép fit", "Tôi phân biệt sai số với bước mã", "Tôi giữ raw data và điều kiện đo"],
    },
]


board.FIGURES.update({
    "a25": '<rect x="35" y="85" width="830" height="310" rx="18" fill="#1e293b"/><g fill="#93c5fd" font-family="Arial" font-size="21"><text x="75" y="135">Nhiệt · TMP36 / DS18B20</text><text x="75" y="200">Ánh sáng · OPT3001</text><text x="75" y="265">Từ · DRV5032</text><text x="480" y="135">Áp suất · BMP280</text><text x="480" y="200">Chuyển động · LSM6DSOX</text><text x="480" y="265">Khoảng cách · VL53L1X</text></g><g fill="#e2e8f0" font-family="Arial" font-size="18"><text x="75" y="350">VOUT · 1-Wire · I²C · mức số</text><text x="480" y="350">I²C/SPI · I²C</text></g>',
    "a26": '<rect x="35" y="85" width="830" height="310" rx="18" fill="#1e293b"/><g fill="#93c5fd" font-family="Arial" font-size="23"><text x="65" y="145">NHIỆT</text><text x="65" y="230">ÁNH SÁNG</text><text x="65" y="315">TỪ</text></g><g fill="#e2e8f0" font-family="Arial" font-size="21"><text x="280" y="145">TMP36 analog ↔ DS18B20 1-Wire</text><text x="280" y="230">OPT3001 lux ↔ LDR chia áp</text><text x="280" y="315">DRV5032 Hall ↔ reed switch</text></g>',
    "a27": '<rect x="35" y="85" width="830" height="310" rx="18" fill="#1e293b"/><g fill="#93c5fd" font-family="Arial" font-size="23"><text x="70" y="145">BMP280</text><text x="70" y="225">LSM6DSOX</text><text x="70" y="305">VL53L1X</text></g><g fill="#e2e8f0" font-family="Arial" font-size="20"><text x="285" y="145">Khí áp 300–1100 hPa · I²C/SPI</text><text x="285" y="225">Gia tốc + tốc độ góc · I²C/SPI</text><text x="285" y="305">ToF · I²C, I/O mặc định 1,8 V</text></g>',
    "a28": '<rect x="35" y="85" width="830" height="310" rx="18" fill="#1e293b"/><path d="M130 332 L750 123" fill="none" stroke="#fbbf24" stroke-width="4"/><path d="M130 336 L750 125" fill="none" stroke="#34d399" stroke-width="3" stroke-dasharray="10 7"/><g fill="#93c5fd" font-family="Arial" font-size="20"><text x="67" y="380">0 °C · 0,510 V</text><text x="350" y="380">25 °C · 0,762 V (kiểm)</text><text x="680" y="380">50 °C · 1,005 V</text></g><g fill="#e2e8f0" font-family="Arial" font-size="20"><text x="135" y="145">Vàng: fit · xanh: danh định</text><text x="450" y="112">Sai số kiểm +0,455 °C</text></g><circle cx="130" cy="332" r="8" fill="#fbbf24"/><circle cx="750" cy="123" r="8" fill="#fbbf24"/><circle cx="440" cy="225" r="7" fill="#ef4444"/>',
})

board.LESSONS.extend(LESSONS)

if __name__ == "__main__":
    board.main()
